package jp.example.variablecolorlight;

import net.minecraft.client.gui.GuiButton;
import net.minecraft.client.gui.GuiScreen;
import net.minecraft.client.gui.GuiTextField;
import org.lwjgl.input.Keyboard;
import net.minecraft.util.StatCollector;

public final class GuiBBCL extends GuiScreen {
    private static final String[] PRESET_KEYS={"gui.bbcl.preset.led","gui.bbcl.preset.hps","gui.bbcl.preset.metal_halide","gui.bbcl.preset.fluorescent","gui.bbcl.preset.incandescent"};
    private final ColoredLightData lamp;private final boolean itemEditor,supportsRedstone;private GuiTextField level,kelvin,red,green,blue;private GuiButton mode,powerMode,preset;private int presetIndex=-1;
    public GuiBBCL(TileVariableColorLamp lamp){this(lamp,false,true);}public GuiBBCL(ColoredLightData lamp,boolean itemEditor,boolean supportsRedstone){this.lamp=lamp;this.itemEditor=itemEditor;this.supportsRedstone=supportsRedstone;}
    @Override public void initGui(){Keyboard.enableRepeatEvents(true);buttonList.clear();int cx=width/2;
        mode=new GuiButton(0,cx-75,height/2-86,supportsRedstone?73:150,20,"");buttonList.add(mode);if(supportsRedstone){powerMode=new GuiButton(3,cx+2,height/2-86,73,20,"");buttonList.add(powerMode);}preset=new GuiButton(4,cx-75,height/2+38,150,20,tr("gui.bbcl.preset"));buttonList.add(preset);buttonList.add(new GuiButton(1,cx-75,height/2+94,72,20,tr("gui.bbcl.save")));buttonList.add(new GuiButton(2,cx+3,height/2+94,72,20,tr("gui.bbcl.cancel")));
        level=field(10,cx-10,height/2-44,85,Integer.toString(lamp.getLevel()));kelvin=field(11,cx-10,height/2-18,85,Integer.toString(lamp.getKelvin()));red=field(12,cx-10,height/2+8,40,Integer.toString(lamp.getRed()));green=field(13,cx+35,height/2+8,40,Integer.toString(lamp.getGreen()));blue=field(14,cx+80,height/2+8,40,Integer.toString(lamp.getBlue()));updateMode();}
    private GuiTextField field(int id,int x,int y,int w,String value){GuiTextField f=new GuiTextField(fontRendererObj,x,y,w,18);f.setText(value);f.setMaxStringLength(5);return f;}
    private void updateMode(){mode.displayString=lamp.isRgbMode()?tr("gui.bbcl.rgb"):tr("gui.bbcl.kelvin");if(powerMode!=null)powerMode.displayString=lamp.isRedstoneControlled()?tr("gui.bbcl.redstone"):tr("gui.bbcl.always_on");}
    @Override protected void actionPerformed(GuiButton b){if(b.id==0){lamp.setRgbMode(!lamp.isRgbMode());updateMode();}else if(b.id==3){lamp.setRedstoneControlled(!lamp.isRedstoneControlled());updateMode();}else if(b.id==4){applyNextPreset();}else if(b.id==1){int lv=parse(level.getText(),0,15,lamp.getLevel()),k=parse(kelvin.getText(),1000,20000,lamp.getKelvin()),r=parse(red.getText(),0,255,lamp.getRed()),g=parse(green.getText(),0,255,lamp.getGreen()),bl=parse(blue.getText(),0,255,lamp.getBlue());if(itemEditor){lamp.setKelvin(k);lamp.setRgb(r,g,bl);lamp.setRgbMode(mode.displayString.indexOf("RGB")>=0);lamp.setLevel(lv);NetworkHandler.CHANNEL.sendToServer(new MessageSetItemBBCL(lamp.isRgbMode(),lamp.isRedstoneControlled(),k,r,g,bl,lv));}else NetworkHandler.CHANNEL.sendToServer(new MessageSetBBCL((TileVariableColorLamp)lamp,lamp.isRgbMode(),lamp.isRedstoneControlled(),k,r,g,bl,lv));mc.thePlayer.closeScreen();}else if(b.id==2)mc.thePlayer.closeScreen();}
    private void applyNextPreset(){presetIndex=(presetIndex+1)%PRESET_KEYS.length;int k=4000,r=255,g=255,b=255;boolean rgb=false;if(presetIndex==1){k=2000;r=255;g=145;b=24;rgb=true;}else if(presetIndex==2)k=5500;else if(presetIndex==3)k=4100;else if(presetIndex==4)k=2700;float[] c=ColorUtil.kelvinToRgb(k);if(!rgb){r=(int)(c[0]*255);g=(int)(c[1]*255);b=(int)(c[2]*255);}lamp.setKelvin(k);lamp.setRgb(r,g,b);lamp.setRgbMode(rgb);kelvin.setText(Integer.toString(k));red.setText(Integer.toString(r));green.setText(Integer.toString(g));blue.setText(Integer.toString(b));preset.displayString=tr(PRESET_KEYS[presetIndex]);updateMode();}
    private static int parse(String s,int min,int max,int fallback){try{return Math.max(min,Math.min(max,Integer.parseInt(s)));}catch(Exception e){return fallback;}}
    @Override protected void keyTyped(char c,int key){if(key==Keyboard.KEY_ESCAPE){mc.thePlayer.closeScreen();return;}level.textboxKeyTyped(c,key);kelvin.textboxKeyTyped(c,key);red.textboxKeyTyped(c,key);green.textboxKeyTyped(c,key);blue.textboxKeyTyped(c,key);}
    @Override protected void mouseClicked(int x,int y,int button){super.mouseClicked(x,y,button);level.mouseClicked(x,y,button);kelvin.mouseClicked(x,y,button);red.mouseClicked(x,y,button);green.mouseClicked(x,y,button);blue.mouseClicked(x,y,button);}
    @Override public void updateScreen(){level.updateCursorCounter();kelvin.updateCursorCounter();red.updateCursorCounter();green.updateCursorCounter();blue.updateCursorCounter();}
    @Override public void onGuiClosed(){Keyboard.enableRepeatEvents(false);}
    @Override public void drawScreen(int mx,int my,float tick){drawDefaultBackground();int cx=width/2;drawCenteredString(fontRendererObj,tr("gui.bbcl.title"),cx,height/2-112,0xFFFFFF);drawString(fontRendererObj,tr("gui.bbcl.brightness"),cx-120,height/2-39,0xCCCCCC);drawString(fontRendererObj,tr("gui.bbcl.kelvin_range"),cx-120,height/2-13,0xCCCCCC);drawString(fontRendererObj,tr("gui.bbcl.rgb"),cx-120,height/2+13,0xCCCCCC);level.drawTextBox();kelvin.drawTextBox();red.drawTextBox();green.drawTextBox();blue.drawTextBox();int rr=parse(red.getText(),0,255,lamp.getRed()),gg=parse(green.getText(),0,255,lamp.getGreen()),bb=parse(blue.getText(),0,255,lamp.getBlue());if(!lamp.isRgbMode()){float[] c=ColorUtil.kelvinToRgb(parse(kelvin.getText(),1000,20000,lamp.getKelvin()));rr=(int)(c[0]*255);gg=(int)(c[1]*255);bb=(int)(c[2]*255);}drawRect(cx-75,height/2+64,cx+75,height/2+86,0xFF000000|(rr<<16)|(gg<<8)|bb);super.drawScreen(mx,my,tick);}
    private static String tr(String key){return StatCollector.translateToLocal(key);}
    @Override public boolean doesGuiPauseGame(){return false;}
}
